(define (jailman-help)
  (display
   (string-append
    "* For media management \n"
    "jailman fetch-media  --version <version> \n"
    "jailman remove-media --version <version> \n"
    "jailman list-media \n"
    "\n"
    "* For non-vnet jail creation \n"
    "jailman create --name <jail-name> --version <version> --hostname <hostname> \n"
    "               [--devfs-ruleset <ruleset-num>] \n"
    "               [--interface-addr-ip4 <interface>|<ip4>] \n"
    "* For vnet jail creation \n"
    "jailman create --name <jail-name> --version <version> --hostname <hostname> \n"
    "               [--devfs-ruleset <ruleset-num>] \n"
    "               --vnet \n"
    "               --bridge-interface <interface> \n"
    "               --vent-epaira-ip4 <ip4/mask> --vnet-epairb-ip4 <ip4/mask> \n"
    "* Start and stop jails \n"
    "jailman start  --name <jail-name> \n"
    "jailman stop   --name <jail-name> \n"
    "jailman stopall \n"
    "* Login jails \n"
    "jailman login  --name <jail-name> \n"
    "* List jails \n"
    "jailman list \n"
    "* Remove jails \n"
    "jailman remove --name <jail-name> \n"
    )))
