* Jailman: FreeBSD jail management tool for its own jails

** Jailman

Jailman is a jail management tool only for jails that are generated by
jailman. Jailman enables users to fetch base file, to create, to list,
to start, to login, to stop and to remove jails.


** Types of jails supported

Jailman deals with only thick jails. About network, vnet is
supported. The following schema shows how non-vnet jails and vnet
jails are constructed by jailman.


*** Non-vnet jail

#+BEGIN_EXAMPLE
# (e.g.) assuming host's network interfacde is em0
             ----- Jail -----
             |              |
             |              |
             |              |
             |--------------|
Internet -- em0
             |---- Host ----|
             |              |
             |              |
             |              |
             ----------------
#+END_EXAMPLE

*** vnet jail

#+BEGIN_EXAMPLE
# (e.g.) assuming host's network interfacde is em0
L2 Level
             ----- Host -----           ---- Jail -----
             |              |           |             |
Internet -- em0 ----+----- epair0a--epair0b           |
             |      |       |           |             |
             |   bridge0    |           |             |
             ----------------           ---------------
L3 Level
    NetworkA ---------------  L3 NetworkB
                      10.10.10.1/24 - 10.10.10.11/24 
#+END_EXAMPLE



** Prerequisite

- Gauche Scheme (>= 0.9.15)


*** For vnet jails

- Bridge interface on host
- Allow ip forwarding on host

#+BEGIN_EXAMPLE
# (e.g.)
# assuming host's network interfacde is em0
# prepare new bridge interface and add em0 to it.
# 
# /etc/rc.conf
cloned_interfaces="bridge0"
ifconfig_bridge0="addm em0 up"

gateway_enable="YES"
#+END_EXAMPLE

If your host enables pf (packat filtering), it prevents packet
forwarding even if gateway_enable="YES" is set. In this case, you need
to explicitly forward packet from jail internal network to external
interface as follows by setting pf.conf.

#+BEGIN_EXAMPLE
# /etc/rc.conf
pf_enable="YES"
#+END_EXAMPLE

#+BEGIN_EXAMPLE
# /etc/pf.conf
ext_if = "em0"
jail_net = "10.10.10.0/24"
nat on $ext_if from $jail_net to any -> ($ext_if)
#+END_EXAMPLE

  
** Installation

Clone this repository, give executable permission to the file named
'jailman'. Add the directory to PATH variable.


** Directories

The default directory jailman utilizes is /usr/local/jailman. If
JAILMAN_BASE_DIR is set, the directory is used as the base
directory. The following directories are created when jailman is used.

- <jailman-base-dir>/media/
  - Store downloaded FreeBSD base files
- <jailman-base-dir>/config/
  - Store configurations of each jail
  - The format is Scheme s-expression.
- <jailman-base-dir>/container/
  - Store jail container
- <jailman-base-dir>/running-info/
  - Store information of running jails


** Commands

*** fetch-media

This command fetches FreeBSD base of the version specified. Available
versions can be seen at
https://download.freebsd.org/ftp/releases/. Files are stored under
<jailman-dir>/media/.

- =--version <version>= 
  - This option specifies a version of FreeBSD to fetch 

#+BEGIN_SRC sh
jailman fetch-media --version 14.2-RELEASE
#+END_SRC


*** remove-media

This command removes FreeBSD base version downloaded.

- =--version <version>=
  - This option specifies a version of FreeBSD to remove


*** list-media

This command lists FreeBSD base files downloaded.

#+BEGIN_SRC sh
jailman list-media
#+END_SRC


*** create

This command creates FreeBSD container with the specified name and its
configuration file. The version of FreeBSD is expanded for the
jail. Specified configuration is saved in the configuration file.

- Required options
  - =--name <name>=
    - This name is used for this jail
  - =--version <version>=
    - This version needs to be one of the downloaded versions, meaning
      one of the versions listed by =jailman list-media=
    - (e.g.) 14.2-RELEASE
  - =--hostname <hostname>=
    - Hostname of the jail
- Optional option
  - =--devfs-ruleset <ruleset-num>=
    - devfs rulest number needs to be specified in /etc/devfs.rules or
      /etc/defaults/devfs.rules

    
**** Network related options

Non-vnet jails are created when =--vnet= is not specified. Vnet jails
are created with =--vnet= option.

For non-vnet jails

- =--interface-addr-ip4 <interface|addr>= or =<interface|add/mask>= is
  optinoally specified.
  - format: <interface>|<ipv4> or <interface>|<ipv4>/mask
    (e.g.) em0|192.168.11.11

For vnet jails

- =--vnet= is required
- =--bridge-interface <bridge-interface>= is required.
  - format: bridgeN (e.g.) bridge0
- =--vnet-epaira-ip4 <addr/mask>= is required.
  - format: <ipv4>/<netmask> (e.g.) 10.10.10.1/24 
- =--vnet-epairb-ip4 <addr/mask>= is required.
  - format: <ipv4>/<netmask> (e.g.) 10.10.10.101/24


#+BEGIN_SRC sh
# non-vnet jail
jailman create --name jail01 --version 14.2-RELEASE --hostname jail01

# vnet jail
jailman create --name jailvnet01 --version 14.2-RELEASE --hostname jailvnet01 \
        --vnet --bridge-interface bridge0 \
        --vnet-epaira-ip4 10.10.10.1/24 --vnet-epairb-ip4 10.10.10.11/24
#+END_SRC


*** start

This command starts the specified container with its configuration.

- =--name <name>=
  - This option specifies the jail to start.

#+BEGIN_SRC sh
jailman start --name jail01
#+END_SRC


*** stop

This command stops the specified container with its running information.

- =--name <name>=
  - This option specifies the jail to stop.

#+BEGIN_SRC sh
jailman stop --name jail01
#+END_SRC


*** stopall

This command stops all the running jails managed by jailman

- =--yes=
  - This option skips confirmation.

#+BEGIN_SRC sh
jailman stopall --yes
#+END_SRC


*** login

This command allows users to log in the specified jail if it is
running. Unlike jexec, login shell session is started.

- =--name <name>=
  - This option specifies the jail to log in.
- =--user <user>=
  - This option allows login by the specified user.

#+BEGIN_SRC sh
jailman login --name jail01
jailman login --name jail01 --user admin
#+END_SRC

*** list

This command lists jail conditions managed by jailman. If there are
jails that are not managed by jailman, they are not listed.

#+BEGIN_SRC sh
jailman list
#+END_SRC

*** remove

This command removes the specified name of container and config.

- =--name <name>=
  - This option specifies the jail to remove.

#+BEGIN_SRC sh
jailman remove --name jail01
#+END_SRC


** Contact

Your feedback is welcome.

Maintainer: Toshihiro (Toshi) Umehara toshi@niceume.com
